//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string Order_z { get; set; }
        public Nullable<System.DateTime> Data_z { get; set; }
        public Nullable<System.DateTime> Data_d { get; set; }
        public Nullable<int> PunctV { get; set; }
        public Nullable<int> NameK { get; set; }
        public Nullable<int> CodeFP { get; set; }
        public string Statys { get; set; }
    
        public virtual PunctV PunctV1 { get; set; }
        public virtual User User { get; set; }
    }
}
