//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public string Art { get; set; }
        public string Name { get; set; }
        public string EdIzm { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> MaxDisc { get; set; }
        public string Proizv { get; set; }
        public string Post { get; set; }
        public string Category { get; set; }
        public Nullable<int> DeisDisc { get; set; }
        public Nullable<int> Kolvo { get; set; }
        public string Descript { get; set; }
        public string Photo { get; set; }
        public double? PriceDisc => Price*((100-DeisDisc)*0.01);
    }
}
